@echo off
setlocal
set 1=%~1
set 2=%~2
set 3=%~3
set 4=%~4
set 5=%~5
set 6=%~6
set 7=%~7
set 8=%~8
set 9=%~9
powershell.exe -NOP -EP ByPass -Enc ZgB1AG4AYwB0AGkAbwBuACAAXwBDAFQAXwBCAF8AewAkAEEAcgBnAHMACgB9ADsAXwBDAFQAXwBCAF8AIAAkAEUATgBWADoAMQAgACQARQBOAFYAOgAyACAAJABFAE4AVgA6ADMAIAAkAEUATgBWADoANAAgACQARQBOAFYAOgA1ACAAJABFAE4AVgA6ADYAIAAkAEUATgBWADoANwAgACQARQBOAFYAOgA4ACAAJABFAE4AVgA6ADkA
